## Deletion Methods

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age":          [19, 26, 14, 39, 45, 52, 36],
    "Buy Again?":   [4,  5,  4,  5,  3,  4,  2],
    "Recommend":    [3,  np.nan, 3, 4, 4, 3, 1],
    "Satisfaction": [4,  5,  3,  np.nan, 4, 4, 1],
})

print(df)

   Age  Buy Again?  Recommend  Satisfaction
0   19           4        3.0           4.0
1   26           5        NaN           5.0
2   14           4        3.0           3.0
3   39           5        4.0           NaN
4   45           3        4.0           4.0
5   52           4        3.0           4.0
6   36           2        1.0           1.0

In [3]:
print(f"Before: {df.shape}")

# Drop any row with at least one NaN
df_listwise = df.dropna()
print(f"After listwise deletion: {df_listwise.shape}")
df_listwise

Before: (7, 4)
After listwise deletion: (5, 4)

   Age  Buy Again?  Recommend  Satisfaction
0   19           4        3.0           4.0
2   14           4        3.0           3.0
4   45           3        4.0           4.0
5   52           4        3.0           4.0
6   36           2        1.0           1.0

In [4]:
# Drop only rows where a specific column is NaN
df_subset = df.dropna(subset=["Recommend"])
print(f"After dropping NaN in 'Recommend' only: {df_subset.shape}")
df_subset

After dropping NaN in 'Recommend' only: (6, 4)

   Age  Buy Again?  Recommend  Satisfaction
0   19           4        3.0           4.0
2   14           4        3.0           3.0
3   39           5        4.0           NaN
4   45           3        4.0           4.0
5   52           4        3.0           4.0
6   36           2        1.0           1.0

In [6]:
# In-place
df_copy = df.copy()
df_copy.dropna(how="any", inplace=True)
df_copy

   Age  Buy Again?  Recommend  Satisfaction
0   19           4        3.0           4.0
2   14           4        3.0           3.0
4   45           3        4.0           4.0
5   52           4        3.0           4.0
6   36           2        1.0           1.0

In [9]:
import pandas as pd
import numpy as np

# Drop column 'note' which has >30% missing values
df_iot = pd.read_csv(
    "https://raw.githubusercontent.com/kjam/data-cleaning-101/master/data/iot_example_with_nulls.csv",
    na_values=["n/a"]
)

df_iot.head()

,timestamp,username,temperature,heartrate,build,latest,note
0,2017-01-01T12:00:23,michaelsmith,12.0,67,4e6a7805-8faa-2768-6ef6-eb3198b483ac,0.0,interval
1,2017-01-01T12:01:09,kharrison,6.0,78,7256b7b0-e502-f576-62ec-ed73533c9c84,0.0,wake
2,2017-01-01T12:01:34,smithadam,5.0,89,9226c94b-bb4b-a6c8-8e02-cb42b53e9c90,0.0,NaN
3,2017-01-01T12:02:09,eddierodriguez,28.0,76,NaN,0.0,update
4,2017-01-01T12:02:36,kenneth94,29.0,62,122f1c6a-403c-2221-6ed1-b5caa08f11e0,NaN,NaN

In [12]:
# % of missing values
df_iot.isnull().mean()

timestamp      0.000000
username       0.000000
temperature    0.221022
heartrate      0.000000
build          0.220974
latest         0.220619
note           0.332684
dtype: float64

In [11]:
# Threshold-based column drop
threshold = 0.30
cols_to_drop = df_iot.columns[df_iot.isnull().mean() > threshold].tolist()
print("Dropping columns:", cols_to_drop)

df_col_dropped = df_iot.drop(columns=cols_to_drop)
print(f"Shape before: {df_iot.shape} → after: {df_col_dropped.shape}")
df_col_dropped.head()

Dropping columns: ['note']
Shape before: (146397, 7) → after: (146397, 6)

,timestamp,username,temperature,heartrate,build,latest
0,2017-01-01T12:00:23,michaelsmith,12.0,67,4e6a7805-8faa-2768-6ef6-eb3198b483ac,0.0
1,2017-01-01T12:01:09,kharrison,6.0,78,7256b7b0-e502-f576-62ec-ed73533c9c84,0.0
2,2017-01-01T12:01:34,smithadam,5.0,89,9226c94b-bb4b-a6c8-8e02-cb42b53e9c90,0.0
3,2017-01-01T12:02:09,eddierodriguez,28.0,76,NaN,0.0
4,2017-01-01T12:02:36,kenneth94,29.0,62,122f1c6a-403c-2221-6ed1-b5caa08f11e0,NaN

## Imputation — Univariate

Constant / Arbitrary Value Imputation

In [18]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Embarked": ["S", "C", np.nan, "S", np.nan, "Q"],
    "Fare":     [7.25, 71.28, np.nan, 8.05, 13.0, np.nan],
})

# Fill categorical column with most-common value or a sentinel
df["Embarked_filled"] = df["Embarked"].fillna("No")

# Fill numeric column with 0 (sentinel — not always sensible)
df["Fare_filled_0"] = df["Fare"].fillna(-1)

print(df)

  Embarked   Fare Embarked_filled  Fare_filled_0
0        S   7.25               S           7.25
1        C  71.28               C          71.28
2      NaN    NaN              No          -1.00
3        S   8.05               S           8.05
4      NaN  13.00              No          13.00
5        Q    NaN               Q          -1.00

In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age":    [25, np.nan, 30, 22, np.nan, 35, 28, np.nan],
    "Income": [50000, 120000, np.nan, 45000, 80000, np.nan, 60000, 95000],
    "City":   ["Paris", np.nan, "Lyon", "Paris", np.nan, "Paris", "Lyon", "Paris"],
})

# ── Mean imputation
mean_age = df["Age"].mean()
df["Age_mean"] = df["Age"].fillna(mean_age)
print(f"Mean age: {mean_age:.1f}")

# ── Median imputation
median_income = df["Income"].median()
df["Income_median"] = df["Income"].fillna(median_income)
print(f"Median income: {median_income:,.0f}")

# ── Mode imputation
mode_city = df["City"].mode()[0]
df["City_mode"] = df["City"].fillna(mode_city)
print(f"Mode city: {mode_city}")

Mean age: 28.0
Median income: 70,000
Mode city: Paris

In [20]:
from sklearn.impute import SimpleImputer
# ── Using sklearn SimpleImputer
imputer_mean   = SimpleImputer(strategy="mean")
imputer_median = SimpleImputer(strategy="median")
imputer_mode   = SimpleImputer(strategy="most_frequent")

df["Age_sklearn"]    = imputer_mean.fit_transform(df[["Age"]])
df["Income_sklearn"] = imputer_median.fit_transform(df[["Income"]])

print("\nResult:")
print(df[["Age", "Age_mean", "Age_sklearn", "Income", "Income_median"]].round(1))

Result:
    Age  Age_mean  Age_sklearn    Income  Income_median
0  25.0      25.0         25.0   50000.0        50000.0
1   NaN      28.0         28.0  120000.0       120000.0
2  30.0      30.0         30.0       NaN        70000.0
3  22.0      22.0         22.0   45000.0        45000.0
4   NaN      28.0         28.0   80000.0        80000.0
5  35.0      35.0         35.0       NaN        70000.0
6  28.0      28.0         28.0   60000.0        60000.0
7   NaN      28.0         28.0   95000.0        95000.0